@startuml
!theme reddress-darkblue


class Unidad {
    +Id : int
    +Codigo : string
    +Nombre : string
    +NombreCorto : string
    +Siglas : string
    +ColorPrincipal : string?
    +ColorSecundario : string?
    +Direccion : string?
    +Telefono : string?
    +Email : string?
    +Activo : boolean
    
    -- Colecciones --
    +Propuestas
    +Autoridades
}
Unidad [1] -- [*] Propuesta
Unidad [1] -- [*] Autoridad

class Modalidad {
    +Id : int
    +Codigo : string
    +Nombre : string
    +Descripcion : string?
    +Activo :boolean

    -- Colecciones --
    +Propuestas
}

Modalidad [1] -- [*] Propuesta


class PeriodoLectivo {
    +Id : int
    +Codigo : string
    +Nombre : string
    +Descripcion : string?
    +FechaInicio : datetime
    +FechaFin : datetime
    +Activo : boolean

    -- Colecciones --
    +Propuestas
    +Autoridades
}

PeriodoLectivo [1] -- [*] Propuesta
PeriodoLectivo [1] -- [*] Autoridad

class EstadoAlumno {
    +Id : int
    +Codigo : string
    +Nombre : string
    +Descripcion : string?
    +Activo : boolean

    -- Colecciones --
    +Alumnos
}

class EstadoCertificado {
    +Id : int
    +Codigo : string
    +Nombre : string
    +Descripcion : string?
    +Activo : boolean

    -- Colecciones --
    +Certificados
}

class EstadoInscripcion {
    +Id : int
    +Codigo : string
    +Nombre : string
    +Descripcion : string?
    +Activo : boolean

    -- Colecciones --
    +Inscripciones
}

class EstadoPreinscripcion {
    +Id : int
    +Codigo : string
    +Nombre : string
    +Descripcion : string?
    +Activo : boolean

    -- Colecciones --
    +Preinscripciones
}


class Alumno {
    +Id : int
    +Uuid : Guid
    +TipoDocumentoId : int
    +EstadoAlumnoId : int
    +NumDocumento: string
    +Apellido : string
    +Nombre : string
    +FechaNacimiento : datetime
    +Sexo : string?
    +Email : string?
    +Telefono : string?
    +Domicilio : string?
    +CodigoPostal : string?
    +Ciudad : string?
    +Provincia : string?
    +Pais : string?
    +CiudadNacimiento : string?
    +Colegio : string?
    +Profesion : string?
    +LugarTrabajo : string?
    +NumeroSocio : string?
    +EsSocio : string?
    +Activo : boolean
    +CreadoEn : datetime
    +ActualizadoEn : datetime

    --Navegavion--
    +TipoDocumento
    +EstadoAlumno

    --Colecciones--
    +Certificados
    +Inscripciones
    +Preinscripciones
}


Alumno [*] -- [1] EstadoAlumnoId 
Alumno [*] -- [1] TipoDocumentoId
Alumno [1] -- [*] Certificado
Alumno [1] -- [*] Inscripciones
Alumno [1] -- [*] Preinscripciones



@enduml







