INSERT INTO portales (propuesta_id, titulo_web, slug, banner_img, acerca_de, perfil_estudiante, requisitos, destinatarios, fundamentacion, etiquetas, meta_og_title, meta_og_image, meta_description, meta_keywords, visitas) VALUES
-- Propuesta 1: Diplomatura en Ortodoncia
(1, 'Diplomatura en Ortodoncia y Ortopedia Maxilar - Especialízate en Salud Bucal', 'diplomatura-ortodoncia-2024', 'banner-ortodoncia.jpg',
 'Programa de especialización integral en diagnóstico y tratamiento de maloclusiones dentofaciales. Formación práctica con enfoque contemporáneo y evidencia científica actualizada.',
 'Odontólogos generales con interés en especialización, profesionales que buscan actualizar conocimientos en ortodoncia, egresados recientes de odontología.',
 'Título de Odontólogo, matrícula profesional habilitante, CV actualizado, entrevista de admisión, compromiso de asistencia.',
 'Odontólogos generales, especialistas en otras áreas odontológicas, estudiantes avanzados de odontología (último año).',
 'Esta diplomatura te ofrece actualización científica, habilidades prácticas en técnicas modernas, mejora tu valor profesional y abre oportunidades en consultorio propio o instituciones de salud.',
 'ortodoncia, odontología, postgrado, salud bucal, dientes, tratamiento, especialización, medicina',
 'Diplomatura en Ortodoncia 2024 - Universidad Católica de Cuyo',
 'og-ortodoncia.jpg',
 'Especialízate en ortodoncia con nuestro programa integral. Docentes expertos, enfoque práctico. Inscripciones abiertas para 2024.',
 'diplomatura ortodoncia, curso odontología, postgrado odontología, salud dental, especialización dental, universidad san juan',
 1250),

-- Propuesta 2: Curso de Hipertensión Arterial
(2, 'Curso de Actualización: Hipertensión Arterial - Manejo Integral del Paciente Hipertenso', 'hipertension-arterial-2024', 'banner-hipertension.jpg',
 'Actualización intensiva en enfoque diagnóstico y terapéutico de la hipertensión arterial. Protocolos basados en las últimas guías clínicas internacionales.',
 'Médicos generalistas, clínicos, cardiólogos, residentes de medicina interna, profesionales de la salud interesados en cardiología.',
 'Título de médico, matrícula profesional, interés en medicina cardiovascular, disponibilidad para actividades sincrónicas.',
 'Médicos de todas las especialidades, residentes de clínica médica y cardiología, profesionales de enfermería especializada.',
 'Actualiza tu práctica clínica con las últimas evidencias, mejora el pronóstico de tus pacientes, obtén certificación universitaria y aumenta tu competencia profesional.',
 'hipertensión, cardiología, medicina, curso médico, actualización, salud cardiovascular, presión arterial',
 'Curso Hipertensión Arterial 2024 - UCCuyo Medicina',
 'og-hipertension.jpg',
 'Actualización en hipertensión arterial para médicos. Guías actuales, manejo integral. Modalidad virtual con expertos.',
 'hipertensión arterial, curso médicos, cardiología, presión alta, medicina clínica, actualización médica',
 890),

-- Propuesta 3: Simposio Internacional de Educación
(3, 'Simposio Internacional de Educación - Innovación y Tendencias Pedagógicas 2024', 'simposio-educacion-2024', 'banner-educacion.jpg',
 'Espacio de reflexión y actualización sobre innovación educativa, tecnologías emergentes y tendencias pedagógicas del siglo XXI. Conferencias magistrales internacionales.',
 'Docentes de todos los niveles educativos, directivos escolares, coordinadores pedagógicos, estudiantes de carreras docentes, investigadores en educación.',
 'Inscripción previa, interés en innovación educativa, no se requieren títulos específicos para asistencia general.',
 'Educadores, directivos, estudiantes de profesorado, pedagogos, psicopedagogos, diseñadores instruccionales, profesionales de la educación.',
 'Accede a conocimientos de vanguardia, conoce experiencias internacionales exitosas, amplía tu red profesional y renueva tu práctica docente con herramientas concretas.',
 'educación, simposio, innovación, pedagogía, tecnología educativa, jornada, docentes, enseñanza',
 'Simposio Internacional de Educación 2024 - UCCuyo',
 'og-educacion.jpg',
 'Participa del Simposio Internacional de Educación 2024. Innovación, tecnología y nuevas pedagogías. Expertos nacionales e internacionales.',
 'simposio educación, innovación educativa, tecnología educación, pedagogía, jornada docentes, conferencias educación',
 2100),

-- Propuesta 4: Enfermería en Cuidados Críticos
(4, 'Enfermería en Cuidados Críticos - Especialización en Unidades de Terapia Intensiva', 'enfermeria-cuidados-criticos-2024', 'banner-enfermeria.jpg',
 'Formación especializada en cuidados de pacientes críticos, manejo de tecnología de avanzada y protocolos de seguridad en unidades de terapia intensiva.',
 'Licenciados en Enfermería, enfermeros profesionales, estudiantes avanzados de enfermería con interés en cuidados críticos.',
 'Título de enfermero o licenciado en enfermería, matrícula profesional, experiencia mínima de 1 año en servicios de salud.',
 'Enfermeros de hospitales públicos y privados, personal de unidades de terapia intensiva, emergencias y cuidados críticos.',
 'Especialízate en un área de alta demanda laboral, mejora tus competencias en situaciones críticas, aumenta tu valor profesional y accede a mejores oportunidades laborales.',
 'enfermería, cuidados críticos, terapia intensiva, uti, salud, especialización, hospital',
 'Especialización en Enfermería de Cuidados Críticos - UCCuyo',
 'og-enfermeria.jpg',
 'Especialízate en cuidados críticos con nuestro programa para enfermeros. Formación práctica en hospitales. Inicio mayo 2024.',
 'enfermería cuidados críticos, uti, terapia intensiva, especialización enfermería, salud hospitalaria',
 750),

-- Propuesta 5: Jornadas de Emergentología Pediátrica
(5, 'Jornadas de Emergentología Pediátrica - Actualización en Urgencias Infantiles', 'emergentologia-pediatrica-2024', 'banner-emergentologia.jpg',
 'Actualización intensiva en manejo inicial del paciente pediátrico en situación de emergencia. Talleres prácticos de RCP y estabilización.',
 'Médicos emergencistas, pediatras, médicos generalistas, residentes de pediatría, personal de servicios de emergencia.',
 'Título de médico o estudiante avanzado de medicina, interés en emergencias pediátricas, inscripción previa obligatoria.',
 'Médicos de guardia, pediatras, emergentólogos, residentes, enfermeros de emergencias, técnicos en emergencias.',
 'Actualiza protocolos de emergencia infantil, aprende técnicas de RCP pediátrico actualizadas, mejora tu respuesta en situaciones críticas y obtén certificación con puntaje.',
 'emergencias, pediatría, rcp, urgencias, niños, salud infantil, jornada médica',
 'Jornadas de Emergentología Pediátrica 2024 - UCCuyo',
 'og-emergentologia.jpg',
 'Actualización en emergencias pediátricas para médicos. RCP, trauma, estabilización. Jornada presencial con expertos.',
 'emergentología pediátrica, urgencias niños, rcp pediátrico, emergencias infantiles, curso médicos',
 520),

-- Propuesta 6: Curso de Lectocomprensión en Inglés
(6, 'Curso de Lectocomprensión en Idioma Inglés - Lectura de Textos Académicos', 'lectocomprension-ingles-2024', 'banner-ingles.jpg',
 'Desarrollo de habilidades de lectura y comprensión de textos académicos y científicos en inglés. Enfoque en vocabulario técnico y estructuras complejas.',
 'Estudiantes universitarios de todas las carreras, investigadores, profesionales que necesitan leer bibliografía en inglés, docentes universitarios.',
 'Nivel básico de inglés (A2 mínimo), acceso a computadora con internet, compromiso de 4-6 horas semanales de estudio.',
 'Estudiantes de grado y posgrado, investigadores, profesionales que publican o leen en inglés, docentes que usan bibliografía internacional.',
 'Accede a información científica actualizada, mejora tu producción académica, cumple con requisitos de posgrado y aumenta tus oportunidades de investigación internacional.',
 'inglés, lectura, comprensión, académico, idiomas, universidad, textos científicos',
 'Curso Lectocomprensión Inglés 2024 - UCCuyo',
 'og-ingles.jpg',
 'Aprende a leer textos académicos en inglés. Vocabulario técnico, comprensión avanzada. Modalidad virtual flexible.',
 'lectura inglés, comprensión textos, inglés académico, curso idiomas, universidad, inglés científico',
 680),

-- Propuesta 7: Diplomatura en Mercado de Capitales
(7, 'Diplomatura en Mercado de Capitales - Finanzas e Inversiones Profesionales', 'mercado-capitales-2024', 'banner-finanzas.jpg',
 'Formación integral en instrumentos financieros, análisis bursátil y estrategias de inversión en el mercado de capitales argentino e internacional.',
 'Contadores públicos, economistas, administradores de empresas, estudiantes avanzados de carreras económicas, asesores financieros.',
 'Título universitario o estudiante avanzado (últimos dos años), conocimientos básicos de economía y matemáticas financieras.',
 'Profesionales del sector financiero, asesores de inversiones, contadores, economistas, emprendedores, interesados en inversiones.',
 'Domina los instrumentos financieros actuales, aprende a gestionar portafolios de inversión, certificación con validez profesional y acceso a bolsa de comercio.',
 'finanzas, mercado capitales, inversiones, bolsa, economía, contabilidad, trading',
 'Diplomatura en Mercado de Capitales 2024 - UCCuyo',
 'og-finanzas.jpg',
 'Especialízate en mercado de capitales. Análisis técnico, instrumentos financieros, estrategias de inversión. Inicio marzo 2024.',
 'mercado capitales, diplomatura finanzas, inversiones, análisis bursátil, bolsa, economía',
 1100),

-- Propuesta 8: Talleres de Robótica Educativa
(8, 'Talleres de Robótica Educativa - Nivel Inicial para Niños', 'robotica-ninos-2024', 'banner-robotica.jpg',
 'Introducción a la robótica educativa mediante proyectos lúdicos y creativos. Desarrollo de pensamiento computacional y resolución de problemas.',
 'Niños y niñas de 9 a 12 años con interés en tecnología, computación y construcción. No se requieren conocimientos previos.',
 'Edad entre 9 y 12 años, interés por la tecnología, autorización de padres/tutores, no requiere conocimientos previos de programación.',
 'Niños en edad escolar, estudiantes de primaria, hijos de docentes y comunidad universitaria, instituciones educativas.',
 'Desarrolla habilidades STEM desde temprana edad, fomenta la creatividad y resolución de problemas, prepara para el futuro tecnológico de manera divertida.',
 'robótica, niños, tecnología, educación, taller, programación, lego, steam',
 'Talleres de Robótica para Niños 2024 - UCCuyo',
 'og-robotica.jpg',
 'Talleres de robótica educativa para niños 9-12 años. Aprendizaje lúdico con LEGO. Inscripciones abiertas.',
 'robótica niños, taller tecnología, programación niños, steam educación, lego educación',
 950),

-- Propuesta 9: Talleres de Programación para Docentes
(9, 'Talleres de Programación para Docentes - Integración Tecnológica en el Aula', 'programacion-docentes-2024', 'banner-programacion.jpg',
 'Capacitación en herramientas de programación educativa para aplicación directa en el aula. Scratch, Python y recursos digitales para la enseñanza.',
 'Docentes de todos los niveles educativos, coordinadores TIC, directivos escolares, estudiantes de profesorado.',
 'Ser docente activo o estudiante de profesorado, acceso a computadora, interés en innovación educativa, no requiere conocimientos previos de programación.',
 'Docentes de primaria y secundaria, profesores universitarios, coordinadores pedagógicos, educadores no formales.',
 'Actualiza tus métodos de enseñanza, incorpora tecnología de manera pedagógica, motiva a tus estudiantes y prepáralos para el futuro digital.',
 'programación, docentes, educación, tecnología, scratch, python, aula digital',
 'Programación para Docentes 2024 - UCCuyo',
 'og-programacion.jpg',
 'Capacitación en programación para docentes. Herramientas prácticas para el aula. Certificación ministerial.',
 'programación docentes, tecnología educativa, scratch, python, aula digital, capacitación docentes',
 720),

-- Propuesta 10: Talleres de Arduino - Proyectos Avanzados
(10, 'Talleres de Arduino - Proyectos Avanzados de Electrónica y Programación', 'arduino-avanzado-2024', 'banner-arduino.jpg',
 'Desarrollo de proyectos complejos con Arduino, sensores avanzados y aplicaciones IoT. Enfoque práctico en automatización y sistemas embebidos.',
 'Estudiantes secundarios y universitarios, makers, aficionados a la electrónica, docentes de tecnología, ingenieros en formación.',
 'Conocimientos básicos de electrónica y programación, haber realizado algún proyecto previo con Arduino o similar, edad mínima 16 años.',
 'Estudiantes de ingeniería, electrónica, informática; makers y hobbistas; docentes de tecnología; emprendedores tecnológicos.',
 'Desarrolla proyectos reales de automatización, aprende IoT aplicado a situaciones concretas, crea prototipos funcionales y amplía tu portafolio de habilidades técnicas.',
 'arduino, electrónica, programación, iot, proyectos, automatización, makers',
 'Talleres Arduino Avanzado 2024 - UCCuyo',
 'og-arduino.jpg',
 'Talleres avanzados de Arduino. Proyectos IoT, sensores, automatización. Laboratorios equipados. Cupos limitados.',
 'arduino, electrónica, iot, programación, proyectos, automatización, taller tecnología',
 610),

-- Propuesta 11: Maestría en Derecho Penal
(11, 'Maestría en Derecho Penal - Especialización Profundizada 2025', 'maestria-derecho-penal-2025', 'banner-derecho.jpg',
 'Programa de posgrado avanzado en teoría del delito, proceso penal y criminología. Formación de alto nivel académico con enfoque práctico.',
 'Abogados, fiscales, defensores, jueces, estudiantes avanzados de derecho, profesionales del sistema penal.',
 'Título de abogado o estudiante del último año de derecho, CV académico, carta de motivación, entrevista de admisión.',
 'Profesionales del derecho penal, funcionarios judiciales, académicos, investigadores en ciencias penales, asesores legales.',
 'Profundiza en la teoría penal contemporánea, especialízate para litigio complejo, accede a nivel académico superior y mejora tu posición en el sistema judicial.',
 'derecho penal, maestría, abogacía, justicia, criminología, proceso penal, posgrado derecho',
 'Maestría en Derecho Penal 2025 - UCCuyo',
 'og-derecho.jpg',
 'Maestría en Derecho Penal 2025. Especialización avanzada con docentes destacados. Inscripciones abiertas.',
 'maestría derecho penal, posgrado abogacía, especialización penal, criminología, justicia',
 480),

-- Propuesta 12: Tecnicatura en Enología
(12, 'Tecnicatura Universitaria en Enología - Elaboración de Vinos de Calidad', 'tecnicatura-enologia-2024', 'banner-enologia-tecnicatura.jpg',
 'Formación técnica integral en viticultura, vinificación y análisis de vinos. Prácticas en bodegas y laboratorios especializados.',
 'Egresados de nivel secundario, trabajadores del sector vitivinícola, emprendedores en enología, amantes del vino que buscan profesionalizarse.',
 'Secundario completo, interés demostrado en producción vitivinícola, disponibilidad para prácticas en bodega, examen de ingreso.',
 'Jóvenes egresados del secundario, trabajadores de bodegas, emprendedores vitivinícolas, técnicos agrícolas, turistas enológicos.',
 'Accede a una profesión con alta inserción laboral, aprende de expertos en región vitivinícola líder, desarrolla tu propia línea de productos y certificación universitaria.',
 'enología, vino, tecnicatura, viticultura, bodega, producción, mendoz',
 'Tecnicatura en Enología 2024 - UCCuyo Mendoza',
 'og-enologia-tecnicatura.jpg',
 'Conviértete en enólogo con nuestra tecnicatura. Formación práctica en bodegas mendocinas. Carrera con alta salida laboral.',
 'tecnicatura enología, carrera vinos, viticultura, producción vino, mendoz, bodega',
 850),

-- Propuesta 13: Curso de Marketing Digital
(13, 'Curso Intensivo de Marketing Digital - Estrategias para el Mundo Online', 'marketing-digital-2024', 'banner-marketing.jpg',
 'Programa intensivo en estrategias digitales, redes sociales, SEO y publicidad online. Casos prácticos de empresas reales.',
 'Emprendedores, profesionales de marketing, dueños de PYMES, estudiantes de comunicación y negocios, community managers.',
 'Manejo básico de computadora e internet, interés en negocios digitales, no se requieren conocimientos previos de marketing.',
 'Emprendedores, profesionales independientes, responsables de marketing, estudiantes de negocios, dueños de pequeños negocios.',
 'Aprovecha las oportunidades del comercio digital, aumenta las ventas de tu negocio, adquiere habilidades demandadas y certificación para tu CV.',
 'marketing digital, redes sociales, seo, publicidad online, emprendedores, negocios digitales',
 'Curso Marketing Digital 2024 - UCCuyo',
 'og-marketing.jpg',
 'Domina el marketing digital. SEO, redes sociales, publicidad online. Curso intensivo con casos prácticos.',
 'marketing digital, curso online, redes sociales, seo, publicidad, emprendedores',
 1120),

-- Propuesta 14: Jornada de Actualización Veterinaria
(14, 'Jornada de Actualización en Medicina Veterinaria - San Luis 2024', 'jornada-veterinaria-2024', 'banner-veterinaria.jpg',
 'Actualización en patologías frecuentes, diagnóstico por imágenes y terapéutica avanzada en medicina de grandes y pequeños animales.',
 'Médicos veterinarios, estudiantes avanzados de veterinaria, técnicos veterinarios, profesionales de la salud animal.',
 'Título de veterinario o estudiante avanzado, interés en actualización profesional, inscripción previa obligatoria.',
 'Veterinarios clínicos, de campo, especialistas, estudiantes de últimos años, profesionales de laboratorios veterinarios.',
 'Actualiza protocolos diagnósticos y terapéuticos, conoce nuevas tecnologías veterinarias, intercambia experiencias con colegas y obtén puntaje profesional.',
 'veterinaria, animales, medicina veterinaria, actualización, jornada, san luis, salud animal',
 'Jornada Veterinaria 2024 - UCCuyo San Luis',
 'og-veterinaria.jpg',
 'Actualización en medicina veterinaria para profesionales. Diagnóstico, imágenes, terapéutica. Evento presencial en San Luis.',
 'jornada veterinaria, medicina animales, actualización veterinarios, san luis, salud animal',
 430),

-- Propuesta 15: Diplomatura en Educación Especial
(15, 'Diplomatura en Educación Especial e Inclusiva - Atención a la Diversidad', 'educacion-especial-2025', 'banner-educacion-especial.jpg',
 'Formación especializada en diseño de estrategias inclusivas, adaptaciones curriculares y abordaje de necesidades educativas especiales.',
 'Docentes de todos los niveles, psicopedagogos, psicólogos escolares, profesionales de la salud y educación, estudiantes de carreras afines.',
 'Título docente o afín, experiencia o interés en educación especial, CV y carta de motivación, entrevista de admisión.',
 'Educadores, psicopedagogos, terapistas, directivos escolares, profesionales de equipos de orientación, familias de personas con discapacidad.',
 'Especialízate en un área de creciente demanda, mejora la inclusión educativa real, desarrolla herramientas prácticas y obtén certificación universitaria.',
 'educación especial, inclusión, discapacidad, necesidades educativas, pedagogía, diversidad',
 'Diplomatura Educación Especial 2025 - UCCuyo',
 'og-educacion-especial.jpg',
 'Especialízate en educación inclusiva. Estrategias prácticas, adaptación curricular. Inicio abril 2025.',
 'educación especial, diplomatura, inclusión, discapacidad, necesidades educativas, pedagogía',
 690),

-- Propuesta 16: Seminario de Filosofía Contemporánea
(16, 'Seminario de Filosofía Contemporánea - Debates Actuales del Pensamiento', 'seminario-filosofia-2024', 'banner-filosofia.jpg',
 'Análisis profundo de corrientes filosóficas contemporáneas, autores fundamentales y debates actuales en teoría crítica y hermenéutica.',
 'Estudiantes de filosofía y humanidades, docentes, investigadores, profesionales con interés en pensamiento crítico, público general cultivado.',
 'Interés por la filosofía y el pensamiento crítico, no se requieren títulos específicos, lectura de textos en español.',
 'Estudiantes universitarios, docentes de filosofía, investigadores, profesionales de ciencias sociales, amantes de la filosofía.',
 'Profundiza en el pensamiento contemporáneo, desarrolla capacidad crítica, comprende los fundamentos de debates actuales y enriquece tu perspectiva intelectual.',
 'filosofía, pensamiento, humanidades, seminario, teoría crítica, debate, contemporáneo',
 'Seminario de Filosofía Contemporánea 2024 - UCCuyo',
 'og-filosofia.jpg',
 'Seminario de filosofía contemporánea. Autores clave, debates actuales. Modalidad presencial con expertos.',
 'seminario filosofía, pensamiento contemporáneo, humanidades, teoría crítica, debate filosófico',
 380), -- Archivada

-- Propuesta 17: Curso de Química Analítica
(17, 'Curso Avanzado de Química Analítica Instrumental - Técnicas Modernas', 'quimica-analitica-2024', 'banner-quimica.jpg',
 'Formación especializada en técnicas instrumentales de análisis químico: espectroscopía, cromatografía y métodos electroanalíticos avanzados.',
 'Químicos, bioquímicos, farmacéuticos, ingenieros químicos, estudiantes avanzados de carreras científicas, técnicos de laboratorio.',
 'Título universitario en ciencias o ingeniería, conocimientos básicos de química analítica, interés en investigación o control de calidad.',
 'Profesionales de laboratorios, investigadores, docentes de química, técnicos de control de calidad, estudiantes de posgrado.',
 'Domina técnicas instrumentales demandadas, mejora tu perfil para investigación, actualiza conocimientos tecnológicos y certificación para laboratorios acreditados.',
 'química analítica, instrumentación, laboratorio, análisis, espectroscopía, cromatografía',
 'Curso Química Analítica Instrumental 2024 - UCCuyo',
 'og-quimica.jpg',
 'Especialización en técnicas instrumentales de análisis químico. Laboratorios equipados. Inicio agosto 2024.',
 'química analítica, instrumentación, laboratorio, análisis químico, espectroscopía, cromatografía',
 540),

-- Propuesta 18: Taller de Primeros Auxilios
(18, 'Taller de Primeros Auxilios y RCP Básico - Aprende a Salvar Vidas', 'primeros-auxilios-2024', 'banner-primeros-auxilios.jpg',
 'Taller práctico intensivo de primeros auxilios básicos y reanimación cardiopulmonar (RCP). Certificación oficial con validez nacional.',
 'Público en general, estudiantes, docentes, personal de instituciones, empresas, familias, comunidades organizadas.',
 'Edad mínima 16 años, no se requieren conocimientos previos, ropa cómoda para prácticas, interés en aprender primeros auxilios.',
 'Comunidad universitaria, escuelas, empresas, organizaciones comunitarias, familias, personas responsables de grupos.',
 'Adquiere habilidades para emergencias cotidianas, certificación con validez laboral, aumenta la seguridad en tu entorno y responde efectivamente ante accidentes.',
 'primeros auxilios, rcp, emergencias, salud, seguridad, taller práctico, comunidad',
 'Taller de Primeros Auxilios 2024 - UCCuyo',
 'og-primeros-auxilios.jpg',
 'Aprende primeros auxilios y RCP en taller práctico. Certificación oficial. Abierto a toda la comunidad.',
 'primeros auxilios, rcp, emergencias, salud, taller comunitario, seguridad',
 1250),

-- Propuesta 19: Capacitación en Seguridad Informática
(19, 'Capacitación en Seguridad Informática y Ciberdefensa - Protege tus Sistemas', 'seguridad-informatica-2024', 'banner-seguridad.jpg',
 'Programa especializado en protección de sistemas, análisis de vulnerabilidades, ethical hacking y respuesta a incidentes de ciberseguridad.',
 'Profesionales IT, administradores de sistemas, desarrolladores, estudiantes de informática, responsables de seguridad en organizaciones.',
 'Conocimientos básicos de redes y sistemas operativos, manejo de línea de comandos, interés en seguridad informática.',
 'Administradores de sistemas, desarrolladores, profesionales de TI, estudiantes de informática, responsables de seguridad empresarial.',
 'Especialízate en un área de alta demanda laboral, protege activos digitales críticos, adquiere certificaciones reconocidas y aumenta tu valor profesional en tecnología.',
 'seguridad informática, ciberseguridad, hacking ético, protección datos, it, redes',
 'Capacitación en Seguridad Informática 2024 - UCCuyo',
 'og-seguridad.jpg',
 'Especialización en seguridad informática y ciberdefensa. Ethical hacking, protección de sistemas. Modalidad virtual.',
 'seguridad informática, ciberseguridad, hacking ético, protección datos, it seguridad',
 820),

-- Propuesta 20: Curso de Pastoral Juvenil
(20, 'Curso de Formación en Pastoral Juvenil - Acompañamiento Espiritual', 'pastoral-juvenil-2024', 'banner-pastoral.jpg',
 'Formación integral para el acompañamiento espiritual de jóvenes, dinámicas grupales, y planificación pastoral en contextos educativos y parroquiales.',
 'Agentes pastorales, catequistas, docentes de educación religiosa, líderes juveniles, seminaristas, religiosos y laicos comprometidos.',
 'Interés en pastoral juvenil, compromiso eclesial, experiencia básica en trabajo con jóvenes, carta de recomendación parroquial o institucional.',
 'Agentes pastorales, catequistas, docentes de religión, líderes juveniles, seminaristas, religiosas, familias comprometidas.',
 'Profundiza tu formación pastoral, aprende metodologías actuales para jóvenes, obtén herramientas para el acompañamiento espiritual y certificación eclesial reconocida.',
 'pastoral, jóvenes, espiritualidad, religión, catequesis, formación, iglesia',
 'Curso de Pastoral Juvenil 2024 - UCCuyo',
 'og-pastoral.jpg',
 'Formación especializada en pastoral juvenil. Acompañamiento espiritual, dinámicas grupales. Certificación eclesial.',
 'pastoral juvenil, formación pastoral, jóvenes iglesia, catequesis, espiritualidad',
 590),

-- Propuesta 21: Diplomatura en Gestión Pública
(21, 'Diplomatura en Gestión Pública y Administración Gubernamental', 'gestion-publica-2025', 'banner-gestion-publica.jpg',
 'Formación especializada en administración pública, políticas de gobierno, gestión presupuestaria y liderazgo en organizaciones estatales.',
 'Funcionarios públicos, políticos, asesores gubernamentales, estudiantes de ciencias políticas, profesionales interesados en gestión estatal.',
 'Título universitario o experiencia en gestión pública, interés en administración gubernamental, CV y carta de motivación.',
 'Funcionarios municipales, provinciales y nacionales, concejales, asesores legislativos, estudiantes de ciencias políticas, dirigentes sociales.',
 'Mejora tu gestión en el sector público, adquiere herramientas para políticas efectivas, amplía tu red de contactos y certificación universitaria para carrera pública.',
 'gestión pública, administración, gobierno, políticas públicas, estado, funcionarios',
 'Diplomatura en Gestión Pública 2025 - UCCuyo San Luis',
 'og-gestion-publica.jpg',
 'Especialización en gestión pública y administración gubernamental. Modalidad híbrida. Inicio abril 2025.',
 'gestión pública, administración gobierno, políticas públicas, estado, funcionarios',
 460),

-- Propuesta 22: Taller de Cerveza Artesanal
(22, 'Taller de Elaboración de Cerveza Artesanal - De la Malta a la Botella', 'cerveza-artesanal-2024', 'banner-cerveza.jpg',
 'Taller práctico completo de elaboración de cerveza artesanal: desde selección de ingredientes hasta embotellado y comercialización.',
 'Aficionados a la cerveza artesanal, emprendedores gastronómicos, bartenders, cocineros, público general interesado en producción cervecera.',
 'Edad mínima 21 años, interés en cerveza artesanal, no se requieren conocimientos previos, autorización para consumo moderado durante cata.',
 'Aficionados a la cerveza, emprendedores gastronómicos, bartenders, estudiantes de gastronomía, productores caseros, turistas enológicos.',
 'Aprende a producir tu propia cerveza, desarrolla proyectos de microcervecería, obtén certificación para emprendimientos y disfruta de la cultura cervecera.',
 'cerveza artesanal, elaboración, taller, gastronomía, emprendimiento, cata, producción',
 'Taller de Cerveza Artesanal 2024 - UCCuyo Mendoza',
 'og-cerveza.jpg',
 'Aprende a elaborar cerveza artesanal. Taller práctico completo. Planta piloto en Mendoza. Cupos limitados.',
 'cerveza artesanal, taller cerveza, elaboración, gastronomía, emprendimiento, mendoz',
 780),

-- Propuesta 23: Curso de Inglés para Negocios
(23, 'Curso de Inglés para Negocios y Comercio Internacional', 'ingles-negocios-2024', 'banner-ingles-negocios.jpg',
 'Desarrollo de competencias lingüísticas específicas para negocios internacionales: reuniones, presentaciones, negociación y comunicación empresarial.',
 'Profesionales que trabajan con empresas internacionales, empresarios, comerciantes, estudiantes de negocios, ejecutivos.',
 'Nivel intermedio de inglés (B1 mínimo), interés en negocios internacionales, acceso a computadora con micrófono y cámara.',
 'Empresarios, ejecutivos, profesionales de comercio exterior, estudiantes de negocios, emprendedores con proyección internacional.',
 'Mejora tu comunicación en contextos empresariales internacionales, aumenta oportunidades de negocio global, certificación para CV ejecutivo y preparación para entrevistas en inglés.',
 'inglés negocios, comercio internacional, idiomas, empresas, ejecutivos, comunicación empresarial',
 'Curso Inglés para Negocios 2024 - UCCuyo',
 'og-ingles-negocios.jpg',
 'Inglés especializado para negocios internacionales. Comunicación empresarial, negociación. Modalidad virtual.',
 'inglés negocios, comercio internacional, idiomas empresas, comunicación ejecutiva, inglés profesional',
 510), -- Archivada

-- Propuesta 24: Jornada de Innovación Tecnológica
(24, 'Jornada de Innovación Tecnológica y Emprendedurismo 2024', 'innovacion-tecnologica-2024', 'banner-innovacion.jpg',
 'Evento anual que reúne a expertos en tecnología, innovación y emprendimiento. Charlas magistrales, workshops prácticos y ronda de inversión.',
 'Emprendedores tecnológicos, desarrolladores, inversores, estudiantes de ingeniería y negocios, profesionales IT, empresarios innovadores.',
 'Inscripción previa obligatoria, interés en tecnología e innovación, pueden asistir estudiantes, profesionales y público general.',
 'Startups, emprendedores, desarrolladores, inversores, estudiantes universitarios, empresarios, académicos en tecnología.',
 'Conoce tendencias tecnológicas actuales, establece contactos clave, presenta tu proyecto a inversores y accede a oportunidades de networking de alto nivel.',
 'innovación, tecnología, emprendedurismo, startups, jornada, charlas, networking',
 'Jornada de Innovación Tecnológica 2024 - UCCuyo',
 'og-innovacion.jpg',
 'Evento anual de innovación y tecnología. Charlas de expertos, networking, oportunidades de negocio. Noviembre 2024.',
 'innovación tecnológica, emprendedurismo, startups, jornada tecnología, networking empresarial',
 1650),

-- Propuesta 25: Capacitación en Manipulación de Alimentos
(25, 'Capacitación en Manipulación Higiénica de Alimentos - Certificación Obligatoria', 'manipulacion-alimentos-2024', 'banner-alimentos.jpg',
 'Capacitación obligatoria según código alimentario argentino. Buenas prácticas de manufactura, higiene personal y manipulación segura de alimentos.',
 'Trabajadores de la industria alimentaria, cocineros, camareros, dueños de comercios gastronómicos, estudiantes de gastronomía.',
 'Mayor de 18 años, no se requieren conocimientos previos, interés en seguridad alimentaria, documento de identidad.',
 'Trabajadores de restaurantes, comedores, industrias alimenticias, ferias, delivery, estudiantes de gastronomía, emprendedores alimenticios.',
 'Cumple con requisitos legales obligatorios, garantiza seguridad alimentaria, evita multas y cierres, certificación con validez nacional y mejora la calidad de tu servicio.',
 'manipulación alimentos, higiene, gastronomía, seguridad alimentaria, capacitación, alimentos',
 'Capacitación Manipulación de Alimentos 2024 - UCCuyo',
 'og-alimentos.jpg',
 'Capacitación obligatoria en manipulación higiénica de alimentos. Certificación oficial. Modalidad semipresencial.',
 'manipulación alimentos, higiene alimentaria, seguridad alimentos, capacitación gastronomía, certificación alimentos',
 920);