-- Preinscripciones para Diplomatura en Ortodoncia (propuesta = 1)
INSERT INTO inscripciones (documento, apellido, nombre, apellido_nombre, email, telefono, ciudad, pais, fecha_nacimiento, ciudad_nacimiento, sexo, domicilio, codigo_postal, provincia, profesion, lugar_trabajo, edad, fecha_inscripcion, baja, numero_socio, es_socio, pago_mercadopago, propuesta_id, modalidad_id, tipo_estado_inscripcion_id, tipo_documento_id) VALUES
('30932756', 'Mejibar Rivas', 'Maria del Valle', 'Mejibar Rivas Maria del Valle', 'valle_mb@hotmail.com', '2645652502', 'San Juan', 'Argentina', '1984-07-15', 'San Juan', 'F', 'Independencia s/n sur', '5425', 'San Juan', 'Odontóloga', 'Consultorio Privado', 39, NOW(), FALSE, '', '0', FALSE, 1, 1, 1, 1),
('34407353', 'Romarion Alvarado', 'Jesica Paola', 'Romarion Alvarado Jesica Paola', 'jesica.romarion@gmail.com', '154158067', 'San Juan', 'Argentina', '1989-05-06', 'San Juan', 'F', 'Barrio natania xv mza29 casa5', '5407', 'San Juan', 'Odontóloga', 'Hospital Central', 34, NOW(), FALSE, '', '0', FALSE, 1, 1, 1, 1),
('29996789', 'Ibazeta', 'Carolina Soledad', 'Ibazeta Carolina Soledad', 'carol_iba@hotmail.com', '4235597', 'San Juan', 'Argentina', '1983-03-07', 'San Juan', 'F', 'Rodriguez Pinto 2459', '5400', 'San Juan', 'Odontóloga', 'Clínica Dental', 40, NOW(), FALSE, '', '0', FALSE, 1, 1, 1, 1);

-- Preinscripciones para Curso de Actualización: Hipertensión Arterial (propuesta = 2)
INSERT INTO inscripciones (documento, apellido, nombre, apellido_nombre, email, telefono, ciudad, pais, fecha_nacimiento, ciudad_nacimiento, sexo, domicilio, codigo_postal, provincia, profesion, lugar_trabajo, edad, fecha_inscripcion, baja, numero_socio, es_socio, pago_mercadopago, propuesta_id, modalidad_id, tipo_estado_inscripcion_id, tipo_documento_id) VALUES
('32878244', 'Orellano', 'Valeria', 'Orellano Valeria', 'valeritaorellano@hotmail.com', '2645739849', 'San Juan', 'Argentina', '1987-06-29', 'San Juan', 'F', 'Tucuman 1319 norte', '5400', 'San Juan', 'Médica Clínica', 'Hospital Rawson', 36, NOW(), FALSE, '', '0', FALSE, 2, 1, 1, 1),
('34696660', 'Quiroga', 'Maria', 'Quiroga Maria', 'mariafernandaquirogap@gmail.com', '2644778262', 'San Juan', 'Argentina', '1989-09-19', 'San Juan', 'F', 'Cte cabot 496 E barrio Edilco', '2425', 'San Juan', 'Médica', 'Centro de Salud', 34, NOW(), FALSE, '', '0', FALSE, 2, 1, 1, 1),
('32140219', 'Villavicencio', 'Melisa', 'Villavicencio Melisa', 'meli_v07@hotmail.com', '2645058330', 'San Juan', 'Argentina', '1986-03-07', 'San Juan', 'F', 'Barrio 12 de dic. Mbk 4z planta baja D', '5400', 'San Juan', 'Médica', 'Sanatorio Argentino', 37, NOW(), FALSE, '', '0', FALSE, 2, 1, 1, 1);

-- Preinscripciones para Simposio Internacional de Educación (propuesta = 3)
INSERT INTO inscripciones (documento, apellido, nombre, apellido_nombre, email, telefono, ciudad, pais, fecha_nacimiento, ciudad_nacimiento, sexo, domicilio, codigo_postal, provincia, profesion, lugar_trabajo, edad, fecha_inscripcion, baja, numero_socio, es_socio, pago_mercadopago, propuesta_id, modalidad_id, tipo_estado_inscripcion_id, tipo_documento_id) VALUES
('33232102', 'Mulet', 'Yanina', 'Mulet Yanina', 'yanimulet@gmail.com', '154136932', 'San Juan', 'Argentina', '1987-09-09', 'San Juan', 'F', 'H Irigoyen 180 oeste chimbas', '5413', 'San Juan', 'Docente', 'Escuela Normal', 36, NOW(), FALSE, '', '0', FALSE, 3, 1, 1, 1),
('30738038', 'Orellano', 'Natalia', 'Orellano Natalia', 'natiore_23@hotmail.com', '2645127799', 'San Juan', 'Argentina', '1984-07-03', 'San Juan', 'F', 'Tucumán 1319 norte', '5400', 'San Juan', 'Directora', 'Colegio San José', 39, NOW(), FALSE, '', '0', FALSE, 3, 1, 1, 1),
('29003601', 'Sanchez', 'Paz Marcela Fernanda', 'Sanchez Paz Marcela Fernanda', 'marce_s4@hotmail.com', '2644594999', 'San Juan', 'Argentina', '1981-09-04', 'San Juan', 'F', 'Juan maurin 286(N)', '5400', 'San Juan', 'Profesora', 'Instituto Superior', 42, NOW(), FALSE, '', '0', FALSE, 3, 1, 1, 1);

-- Preinscripciones para Enfermería en Cuidados Críticos (propuesta = 4)
INSERT INTO inscripciones (documento, apellido, nombre, apellido_nombre, email, telefono, ciudad, pais, fecha_nacimiento, ciudad_nacimiento, sexo, domicilio, codigo_postal, provincia, profesion, lugar_trabajo, edad, fecha_inscripcion, baja, numero_socio, es_socio, pago_mercadopago, propuesta_id, modalidad_id, tipo_estado_inscripcion_id, tipo_documento_id) VALUES
('30989299', 'Uliarte', 'Gerardo', 'Uliarte Gerardo', 'gerauli18@gmail.com', '2644634674', 'Rawson', 'Argentina', '1984-07-17', 'San Juan', 'M', 'Rawson Centro', '5425', 'San Juan', 'Enfermero', 'Hospital Central', 39, NOW(), FALSE, '', '0', FALSE, 4, 2, 1, 1),
('32808438', 'Lucero', 'Federico', 'Lucero Federico', 'ficolucero@gmail.com', '2646615986', 'San Juan', 'Argentina', '1987-05-22', 'San Juan', 'M', 'Agustin Gómez 999 este', '5400', 'San Juan', 'Enfermero', 'Clínica Modelo', 36, NOW(), FALSE, '', '0', FALSE, 4, 2, 1, 1),
('21402108', 'Polliotto', 'Laura Beatriz', 'Polliotto Laura Beatriz', 'lpolliotto@hotmail.com', '0264-155055478', 'San Juan', 'Argentina', '1966-09-30', 'La Laguna - Córdoba', 'F', 'Pablo Ramella 262 oeste', '5400', 'San Juan', 'Lic. Enfermería', 'Hospital Marcial Quiroga', 57, NOW(), FALSE, '', '0', FALSE, 4, 2, 1, 1);

-- Preinscripciones para Jornadas de Emergentología Pediátrica (propuesta = 5)
INSERT INTO inscripciones (documento, apellido, nombre, apellido_nombre, email, telefono, ciudad, pais, fecha_nacimiento, ciudad_nacimiento, sexo, domicilio, codigo_postal, provincia, profesion, lugar_trabajo, edad, fecha_inscripcion, baja, numero_socio, es_socio, pago_mercadopago, propuesta_id, modalidad_id, tipo_estado_inscripcion_id, tipo_documento_id) VALUES
('28904835', 'Moreno', 'María Daniela', 'Moreno María Daniela', 'mdaniela_81@hotmail.com', '154769666', 'San Juan', 'Argentina', '1981-10-15', 'San Juan', 'F', 'Gral. Paz 1205 oeste', '5400', 'San Juan', 'Médica Pediatra', 'Hospital de Niños', 42, NOW(), FALSE, '', '0', FALSE, 5, 2, 1, 1),
('34921474', 'Mecina', 'Nelba Beatriz', 'Mecina Nelba Beatriz', 'nelba_nel30@hotmail.com', '2644452918', 'San Juan', 'Argentina', '1990-01-30', 'San Juan', 'F', 'Bº CESAP MZ8 BUPA1', '5400', 'San Juan', 'Médica Emergentóloga', 'SAME', 33, NOW(), FALSE, '', '0', FALSE, 5, 2, 1, 1),
('34194520', 'Mery Diaz', 'Cecilia Johana', 'Mery Diaz Cecilia Johana', 'cecilijmery@hotmail.com', '155264108', 'San Juan', 'Argentina', '1989-06-15', 'San Juan', 'F', 'LOS ALMENDROS II, M. A L.4', '5400', 'San Juan', 'Médica', 'Guardia Central', 34, NOW(), FALSE, '', '0', FALSE, 5, 2, 1, 1);

-- Preinscripciones para Curso de Lectocomprensión en Idioma Inglés (propuesta = 6)
INSERT INTO inscripciones (documento, apellido, nombre, apellido_nombre, email, telefono, ciudad, pais, fecha_nacimiento, ciudad_nacimiento, sexo, domicilio, codigo_postal, provincia, profesion, lugar_trabajo, edad, fecha_inscripcion, baja, numero_socio, es_socio, pago_mercadopago, propuesta_id, modalidad_id, tipo_estado_inscripcion_id, tipo_documento_id) VALUES
('35318013', 'Costanza', 'Maria Victoria', 'Costanza Maria Victoria', 'mvictoriacostanza@gmail.com', '02644631170', 'San Juan', 'Argentina', '1990-09-23', 'San Juan', 'F', 'Lavalle 931 Sur', '5400', 'San Juan', 'Estudiante', 'UCCuyo', 33, NOW(), FALSE, '', '0', FALSE, 6, 3, 1, 1),
('35923137', 'Garcia', 'Jazmín', 'Garcia Jazmín', 'jaz.garcia363@gmail.com', '2644464578', 'San Juan', 'Argentina', '1991-06-27', 'San Juan', 'F', 'Belgrano 710 oeste', '5400', 'San Juan', 'Estudiante', 'UNSJ', 32, NOW(), FALSE, '', '0', FALSE, 6, 3, 1, 1),
('30511114', 'Coria', 'Daniela', 'Coria Daniela', 'daniela.a.coria@gmail.com', '2644778374', 'San Juan', 'Argentina', '1983-10-20', 'San Juan', 'F', 'Barrio San Martín', '5400', 'San Juan', 'Profesora', 'Colegio Nacional', 40, NOW(), FALSE, '', '0', FALSE, 6, 3, 1, 1);

-- Preinscripciones para Diplomatura en Mercado de Capitales (propuesta = 7)
INSERT INTO inscripciones (documento, apellido, nombre, apellido_nombre, email, telefono, ciudad, pais, fecha_nacimiento, ciudad_nacimiento, sexo, domicilio, codigo_postal, provincia, profesion, lugar_trabajo, edad, fecha_inscripcion, baja, numero_socio, es_socio, pago_mercadopago, propuesta_id, modalidad_id, tipo_estado_inscripcion_id, tipo_documento_id) VALUES
('30835940', 'Gonzalez', 'Ernesto Humberto Esteban', 'Gonzalez Ernesto Humberto Esteban', 'ehegdj@gmail.com', '2645066515', 'San Juan', 'Argentina', '1984-07-02', 'San Juan', 'M', 'Av benavidez 3074 oeste', '5413', 'San Juan', 'Contador', 'Estudio Contable', 39, NOW(), FALSE, '', '0', FALSE, 7, 1, 1, 1),
('26908424', 'Dorado', 'Silvina Gisela', 'Dorado Silvina Gisela', 'sg_lic.dorado@hotmail.com', '2645703624', 'San Juan', 'Argentina', '1979-02-02', 'San Pedro- Jujuy', 'F', 'Gdor Castro B Sarmiento S 3 Monob 6 PB A', '5423', 'San Juan', 'Lic. Administración', 'Empresa Minera', 44, NOW(), FALSE, '', '0', FALSE, 7, 1, 1, 1),
('30688057', 'Cano', 'Marianela', 'Cano Marianela', 'marianelacano5@gmail.com', '2645268682', 'San Juan', 'Argentina', '1983-12-22', 'San Juan', 'F', 'Barrio los Horneros casa10 mza B', '5425', 'San Juan', 'Economista', 'Banco Provincial', 40, NOW(), FALSE, '', '0', FALSE, 7, 1, 1, 1);

-- Preinscripciones para Talleres de Robótica Educativa (propuesta = 8)
INSERT INTO inscripciones (documento, apellido, nombre, apellido_nombre, email, telefono, ciudad, pais, fecha_nacimiento, ciudad_nacimiento, sexo, domicilio, codigo_postal, provincia, profesion, lugar_trabajo, edad, fecha_inscripcion, baja, numero_socio, es_socio, pago_mercadopago, propuesta_id, modalidad_id, tipo_estado_inscripcion_id, tipo_documento_id) VALUES
('24362882', 'Garay', 'Natalia', 'Garay Natalia', 'nati_garay@hotmail.com', '2644368265', 'San Juan', 'Argentina', '1975-02-21', 'San Juan', 'F', 'B*Soeva 3 mz D con casa 6', '5400', 'San Juan', 'Docente', 'Escuela Primaria', 48, NOW(), FALSE, '', '0', FALSE, 8, 2, 1, 1),
('20943085', 'Yafar', 'Isabel', 'Yafar Isabel', 'Isabelyafar@hotmail.com', '154132484', 'San Juan', 'Argentina', '1969-09-30', 'San Juan', 'F', 'Manuel Zavala 244 Rivadavia', '5400', 'San Juan', 'Directora', 'Jardín de Infantes', 54, NOW(), FALSE, '', '0', FALSE, 8, 2, 1, 1),
('23545567', 'Quiroga', 'Maria Gabriela', 'Quiroga Maria Gabriela', 'mgabiq@hotmail.com', '2646608181', 'San Juan', 'Argentina', '1973-10-12', 'San Juan', 'F', 'Tacuari 2041 oeste', '5400', 'San Juan', 'Profesora', 'Instituto Tecnológico', 50, NOW(), FALSE, '', '0', FALSE, 8, 2, 1, 1);

-- Preinscripciones para Talleres de Programación para Docentes (propuesta = 9)
INSERT INTO inscripciones (documento, apellido, nombre, apellido_nombre, email, telefono, ciudad, pais, fecha_nacimiento, ciudad_nacimiento, sexo, domicilio, codigo_postal, provincia, profesion, lugar_trabajo, edad, fecha_inscripcion, baja, numero_socio, es_socio, pago_mercadopago, propuesta_id, modalidad_id, tipo_estado_inscripcion_id, tipo_documento_id) VALUES
('32140255', 'Bustamante', 'Alejandra', 'Bustamante Alejandra', 'ale_renee22@hotmail.com', '02644100148', 'San Juan', 'Argentina', '1986-08-15', 'San Juan', 'F', 'Avellaneda mbk7 Rivadavia', '5400', 'San Juan', 'Docente', 'Escuela Técnica', 37, NOW(), FALSE, '', '0', FALSE, 9, 3, 1, 1),
('22168877', 'Grecco', 'Mariela Ester', 'Grecco Mariela Ester', 'mpfgrecco@gmail.com', '2645051641', 'San Juan', 'Argentina', '1971-09-06', 'San Juan', 'F', 'Ig de la Roza y Calívar', '5400', 'San Juan', 'Profesora', 'Colegio Secundario', 52, NOW(), FALSE, '', '0', FALSE, 9, 3, 1, 1),
('31366597', 'Santander', 'Micaela', 'Santander Micaela', 'mdvsantander@sanjuan.edu.ar', '264-154468127', 'San Juan', 'Argentina', '1985-09-01', 'San Juan', 'F', 'av. Ignacio de la roza 141 oeste', '5400', 'San Juan', 'Docente', 'Ministerio de Educación', 38, NOW(), FALSE, '', '0', FALSE, 9, 3, 1, 1);

-- Preinscripciones para Talleres de Arduino - Proyectos Avanzados (propuesta = 10)
INSERT INTO inscripciones (documento, apellido, nombre, apellido_nombre, email, telefono, ciudad, pais, fecha_nacimiento, ciudad_nacimiento, sexo, domicilio, codigo_postal, provincia, profesion, lugar_trabajo, edad, fecha_inscripcion, baja, numero_socio, es_socio, pago_mercadopago, propuesta_id, modalidad_id, tipo_estado_inscripcion_id, tipo_documento_id) VALUES
('30932959', 'García', 'Natalia', 'García Natalia', 'natigarcia116@gmail.com', '155136570', 'San Juan', 'Argentina', '1984-09-05', 'San Juan', 'F', 'Gral soler 1954', '5400', 'San Juan', 'Ingeniera', 'Empresa Tecnológica', 39, NOW(), FALSE, '', '0', FALSE, 10, 4, 1, 1),
('35318185', 'Frias', 'Maria Candela', 'Frias Maria Candela', 'candelafrias28@hotmail.com', '4261308', 'San Juan', 'Argentina', '1990-10-28', 'San Juan', 'F', 'Barrio universidad catolica casa 2 manzana j', '5400', 'San Juan', 'Estudiante', 'Facultad de Ingeniería', 33, NOW(), FALSE, '', '0', FALSE, 10, 4, 1, 1),
('36033449', 'Gentili', 'Sabrina', 'Gentili Sabrina', 'sabrigentili07@gmail.com', '0264155842222', 'San Juan', 'Argentina', '1992-03-20', 'San Juan', 'F', 'beethoven 1992 este barrio campodonico', '5411', 'San Juan', 'Desarrolladora', 'Startup Local', 31, NOW(), FALSE, '', '0', FALSE, 10, 4, 1, 1);